apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/managed-gitops/manifests/overlays/stonesoup-member-cluster?ref=f03d1788578567b7596a9df25531ea1c46401801
- ../../openshift-gitops/overlays/production-and-dev
- ../../base/external-secrets
- ../../base/monitoring
- authentication

images:
  - name: \${COMMON_IMAGE}
    newName: quay.io/redhat-appstudio/gitops-service
    newTag: f03d1788578567b7596a9df25531ea1c46401801

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
