apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/release-service/config/default?ref=22f4a01cebe0877c87745dfa098ba3d2868ce6c2

images:
  - name: quay.io/redhat-appstudio/release-service
    newName: quay.io/redhat-appstudio/release-service
    newTag: 22f4a01cebe0877c87745dfa098ba3d2868ce6c2

namespace: release-service
