apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/redhat-appstudio/build-service/config/default?ref=bbec36bdeeb982960017fae072fa9e978014c080

namespace: build-service

images:
- name: quay.io/redhat-appstudio/build-service
  newName: quay.io/redhat-appstudio/build-service
  newTag: bbec36bdeeb982960017fae072fa9e978014c080

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true